from tkinter import*
root=Tk()
root.geometry("350x275")
root.resizable(0,0)
root.title("My Calculator")
calculation=""
def add(op):
    global calculation
    calculation=calculation+str(op)
    text_result.delete(1.0,"end")
    text_result.insert(1.0,calculation)
def evaluate():
    global calculation
    try:
        calculation=str(eval(calculation))
        text_result.delete(1.0,"end")
        text_result.insert(1.0,calculation)
    except:
        clear()
        text_result.insert(1.0,"Error")
def clear():
    global calculation
    calculation=""
    text_result.delete(1.0,"end")
text_result=Text(root,height=2,width=16,font=("Ariel",24))
text_result.grid(columnspan=5)
bt_1=Button(root,text="7",command=lambda:add(7),width=5,font=("Ariel",14),activebackground="green",activeforeground="red")
bt_1.grid(row=2,column=1)
bt_2=Button(root,text="8",command=lambda:add(8),width=5,font=("Ariel",14),activebackground="green",activeforeground="red")
bt_2.grid(row=2,column=2)
bt_3=Button(root,text="9",command=lambda:add(9),width=5,font=("Ariel",14),activebackground="green",activeforeground="red")
bt_3.grid(row=2,column=3)
bt_4=Button(root,text="//",command=lambda:add("//"),width=5,font=("Ariel",14),activebackground="green",activeforeground="red")
bt_4.grid(row=2,column=4)
bt_5=Button(root,text="/",command=lambda:add("/"),width=5,font=("Ariel",14),activebackground="green",activeforeground="red")
bt_5.grid(row=2,column=5)
bt_6=Button(root,text="4",command=lambda:add(4),width=5,font=("Ariel",14),activebackground="green",activeforeground="red")
bt_6.grid(row=3,column=1)
bt_7=Button(root,text="5",command=lambda:add(5),width=5,font=("Ariel",14),activebackground="green",activeforeground="red")
bt_7.grid(row=3,column=2)
bt_8=Button(root,text="6",command=lambda:add(6),width=5,font=("Ariel",14),activebackground="green",activeforeground="red")
bt_8.grid(row=3,column=3)
bt_9=Button(root,text="%",command=lambda:add("%"),width=5,font=("Ariel",14),activebackground="green",activeforeground="red")
bt_9.grid(row=3,column=4)
bt_10=Button(root,text="*",command=lambda:add("*"),width=5,font=("Ariel",14),activebackground="green",activeforeground="red")
bt_10.grid(row=3,column=5)
bt_11=Button(root,text="1",command=lambda:add(1),width=5,font=("Ariel",14),activebackground="green",activeforeground="red")
bt_11.grid(row=4,column=1)
bt_12=Button(root,text="2",command=lambda:add(2),width=5,font=("Ariel",14),activebackground="green",activeforeground="red")
bt_12.grid(row=4,column=2)
bt_13=Button(root,text="3",command=lambda:add(3),width=5,font=("Ariel",14),activebackground="green",activeforeground="red")
bt_13.grid(row=4,column=3)
bt_14=Button(root,text="**",command=lambda:add("**"),width=5,font=("Ariel",14),activebackground="green",activeforeground="red")
bt_14.grid(row=4,column=4)
bt_15=Button(root,text="-",command=lambda:add("-"),width=5,font=("Ariel",14),activebackground="green",activeforeground="red")
bt_15.grid(row=4,column=5)
bt_16=Button(root,text="(",command=lambda:add("("),width=5,font=("Ariel",14),activebackground="green",activeforeground="red")
bt_16.grid(row=5,column=1)
bt_17=Button(root,text="0",command=lambda:add(0),width=5,font=("Ariel",14),activebackground="green",activeforeground="red")
bt_17.grid(row=5,column=2)
bt_18=Button(root,text="00",command=lambda:add("00"),width=5,font=("Ariel",14),activebackground="green",activeforeground="red")
bt_18.grid(row=5,column=3)
bt_19=Button(root,text=")",command=lambda:add(")"),width=5,font=("Ariel",14),activebackground="green",activeforeground="red")
bt_19.grid(row=5,column=4)
bt_20=Button(root,text="+",command=lambda:add("+"),width=5,font=("Ariel",14),activebackground="green",activeforeground="red")
bt_20.grid(row=5,column=5)
bt_21=Button(root,text="C",command=clear,width=10,font=("Ariel",14),activebackground="green",activeforeground="red")
bt_21.grid(row=6,column=1,columnspan=2)
bt_22=Button(root,text="=",command=evaluate,width=10,font=("Ariel",14),activebackground="green",activeforeground="red")
bt_22.grid(row=6,column=3,columnspan=2)
bt_23=Button(root,text=".",command=lambda:add("."),width=5,font=("Ariel",14),activebackground="green",activeforeground="red")
bt_23.grid(row=6,column=5)
root.mainloop()
